import 'controller/cancelnow_controller.dart';import 'package:flutter/material.dart';import 'package:flutter_svg/flutter_svg.dart';import 'package:foodapp/core/app_export.dart';
// ignore_for_file: must_be_immutable
class CancelnowDialog extends StatelessWidget {CancelnowDialog(this.controller);

CancelnowController controller;

@override Widget build(BuildContext context) { return Container(decoration: BoxDecoration(color: ColorConstant.gray50), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.end, children: [Container(width: double.infinity, decoration: BoxDecoration(color: ColorConstant.whiteA700, borderRadius: BorderRadius.circular(getHorizontalSize(20.00))), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, mainAxisAlignment: MainAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: getHorizontalSize(20.00), top: getVerticalSize(21.22), right: getHorizontalSize(20.00)), child: Container(height: getVerticalSize(72.33), width: getHorizontalSize(83.90), child: SvgPicture.asset(ImageConstant.imgGroup18043, fit: BoxFit.fill))), Container(width: getHorizontalSize(227.00), margin: EdgeInsets.only(left: getHorizontalSize(20.00), top: getVerticalSize(23.45), right: getHorizontalSize(20.00)), child: Text("msg_there_s_a_us_5".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.textStyleSofiaProsemibold20.copyWith(fontSize: getFontSize(20)))), Container(width: getHorizontalSize(283.00), margin: EdgeInsets.only(left: getHorizontalSize(20.00), top: getVerticalSize(11.00), right: getHorizontalSize(20.00)), child: Text("msg_jhon_wick_is_fi".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.textStyleSofiaProregular143.copyWith(fontSize: getFontSize(14)))), Padding(padding: EdgeInsets.only(left: getHorizontalSize(20.00), top: getVerticalSize(36.00), right: getHorizontalSize(20.00)), child: GestureDetector(onTap: () {onTapBtnCancelorder();}, child: Container(alignment: Alignment.center, height: getVerticalSize(57.00), width: getHorizontalSize(248.00), decoration: BoxDecoration(color: ColorConstant.deepOrange400, borderRadius: BorderRadius.circular(getHorizontalSize(28.50)), boxShadow: [BoxShadow(color: ColorConstant.deepOrange40040, spreadRadius: getHorizontalSize(2.00), blurRadius: getHorizontalSize(2.00), offset: Offset(0, 20))]), child: Text("lbl_cancel_order".tr, textAlign: TextAlign.center, style: AppStyle.textStyleSofiaProsemibold15.copyWith(fontSize: getFontSize(15), letterSpacing: 1.20))))), Padding(padding: EdgeInsets.only(left: getHorizontalSize(20.00), top: getVerticalSize(22.00), right: getHorizontalSize(20.00), bottom: getVerticalSize(18.00)), child: Text("lbl_skip".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.textStyleSofiaProregular161.copyWith(fontSize: getFontSize(16))))]))])); } 
onTapBtnCancelorder() { Get.toNamed(AppRoutes.favoritesFoodItemsPage); } 
 }
